### ISSUE TITLE
Unable to epoll_ctl() fd -1 to epoll: Bad file descriptor

### ISSUE THREAD

**Issue by aikooo7** [anope/docker#37]
When running default run command I get:

```
[Aug 23 20:34:37 2024] Anope 2.0.16 starting up
[Aug 23 20:34:37 2024] Unable to initialize languages, gettext is not installed
[Aug 23 20:34:37 2024] Loading modules...
[Aug 23 20:34:37 2024] Error while loading ns_resetpass: Not using mail.
[Aug 23 20:34:37 2024] Unable to epoll_ctl() fd -1 to epoll: Bad file descriptor
```

**Comment by sadiepowell** [comment]
Given the issue you've reported with the InspIRCd docker container (https://github.com/inspircd/inspircd-docker/issues/155) I think your Docker host might be broken. Maybe you've reached your file descriptor limit?

**Comment by aikooo7** [comment]
> Given the issue you've reported with the InspIRCd docker container (https://github.com/inspircd/inspircd-docker/issues/155) I think your Docker host might be broken. Maybe you've reached your file descriptor limit?

It might be broken but ergo's docker image and multiple others non-irc related images work so is it very specific.

**Comment by sadiepowell** [comment]
Are they running at the same time? You can't bind to the same ports twice.

**Comment by aikooo7** [comment]
> Are they running at the same time? You can't bind to the same ports twice.

Sorry didn't see your message. No they are not.

**Comment by aikooo7** [comment]
> Given the issue you've reported with the InspIRCd docker container ([inspircd/docker#155](https://github.com/inspircd/docker/issues/155)) I think your Docker host might be broken. Maybe you've reached your file descriptor limit?

I was just able to make linuxserver's ngircd image work, so maybe it is really an issue?

**Comment by aikooo7** [comment]
With this new information, I tried to find out what was different between anope, inspircd and ngircd. I found out that anope and inspircd create a user in the dockerfile and use it but ngircd don't. Removing it and putting the user in the docker compose fixed it.
