### ISSUE TITLE
Is SSL possible?/Connection lost with SSL

### ISSUE THREAD

**Issue by DracoMilesX** [anope/docker#8]
I am trying to configure Anope in combination with the InspIRCd docker.
First Anope successfully connects to the uplink and afterwards directly loses the connection.
With the message that m_spanningtree.so needs to be enabled or SSL has to be configured.

The config site for InspIRCd says "usually" it doesn't work but is it possible with this Anope docker to connect with SSL?

m_spannigtree.so is enabled and as far as I can see SSL is configured (Unless I misread something)
Either way here are my docker runs:

docker run -d \
--name InspIRCd01 \
--hostname inspircd \
--memory=256M \
--memory-swap=384M \
--restart=always \
-p 6697:6697 \
-p 7001:7001 \
-e INSP_NET_SUFFIX=.example.org \
-e INSP_NET_NAME=Omega \
-e INSP_ADMIN_NAME=test \
-e INSP_ADMIN_NICK=test \
-e INSP_ADMIN_EMAIL=test@example.org \
-e INSP_OPER_NAME=God \
-e INSP_OPER_HOST=*@* \
-e INSP_OPER_HASH=hmac-sha256 \
-e INSP_OPER_PASSWORD_HASH='something' \
-e INSP_OPER_SSONLY=yes \
-e INSP_ENABLE_DNSBL=yes \
-e INSP_SERVICES_NAME=services.example.org \
-e INSP_SERVICES_IPADDR=Anope01 \
-e INSP_SERVICES_TLS_ON=yes \
-e INSP_SERVICES_SENDPASS='topsecret' \
-e INSP_SERVICES_RECVPASS='topsecret' \
-e INSP_SERVICES_ALLOWMASK=192.168.1.0/24 \
-v /docker/apps/inspircd:/inspircd/conf/ \
inspircd/inspircd-docker

docker run -d \
--name Anope01 \
--hostname Anope01 \
--memory=256M \
--memory-swap=384M \
--restart=always \
-v /docker/apps/anope:/data \
-e ANOPE_UPLINK_PORT=7001 \
-e ANOPE_SQL_ENGINE=mysql \
-e ANOPE_MYSQL_DB=anope \
-e ANOPE_MYSQL_HOST=192.168.1.10 \
-e ANOPE_MYSQL_PORT=3306 \
-e ANOPE_MYSQL_USER=anope \
-e ANOPE_MYSQL_PASSWORD='anope' \
-e ANOPE_SERVICES_NAME=services.example.org \
-e ANOPE_SERVICES_VHOST=services.example.org \
-e ANOPE_UPLINK_IP=inspircd.example.org \
-e ANOPE_UPLINK_PASSWORD='topsecret' \
anope/anope

**Comment by SISheogorath** [comment]
Right now it's hard-coded off.

https://github.com/Adam-/anope-docker/blob/1da44a0487d0ffdcadf441d75ce92e65e0b207b3/conf/uplink.sh#L23

The whole config management of Anope-docker is far away from being perfect right now. Feel free to file a PR :)

**Comment by DracoMilesX** [comment]
Thanks for the info I just tried it by building the image myself but then I receive in the InspIRCd log that the Handshake Failed - An unexpected TLS packet was received.

But guess might be related that the rest of SSL isn't implemented yet so guess will try to look around.

**Comment by SISheogorath** [comment]
To really use the setting you also have to load the gnutls or openssl module:

https://github.com/anope/anope/blob/8bb3067e427caa92e4b6fc1596198b7bf352656f/data/modules.example.conf#L553-L580

You may want to include it into the main config or change the example config of your setup.
